### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by romanovzky** [jasonwei20/eda_nlp#1]
Hi there,

First of all, great paper. I had thought of similar solutions for DA on text, but I'm glad someone put all of them together!

However, I can't seem to run. First of all, the readme mentions `python code/1_data_process.py` but there is no such file.

By adding `a_`, `b_`, etc suffixes, I get the following errors

```
Using TensorFlow backend.
Traceback (most recent call last):
  File "code/a_1_data_process.py", line 28, in <module>
    gen_sr_aug(train_orig, output_file, alpha, n_aug)
  File "/myworkingdirectory/eda_nlp/code/methods.py", line 173, in gen_sr_aug
    writer = open(output_file, 'w')
FileNotFoundError: [Errno 2] No such file or directory: 'size_data_f1/1_tiny/cr/train_sr_0.05.txt'
``` 

and similar to every possible suffix.

Thanks!

**Comment by jasonwei20** [comment]
Hey Romanov, nice to hear from you. Let me clean this up a little and get back to you soon hahaha

**Comment by jasonwei20** [comment]
Hi, thanks for the note! Please look at the updated readme, the original code on there was very old. Please feel free to reach out if you have any other issues.
