### ISSUE TITLE
experiments section

### ISSUE THREAD

**Issue by AlloyMei** [jasonwei20/eda_nlp#10]
@jasonwei20 , hi, thank you very much for your project,  and I've been waiting for your update. If you can update, thank you very sincerely.

**Comment by jasonwei20** [comment]
You can find the code for experiments in `experiments`
You need to download the datasets on your own (#9)

They are sorted by
- `a`: different alpha (Figure 3 in the paper)
- `b`: dataset increments (Figure 1 in the paper)
- `c`: different dataset sizes (Table 2 in the paper)
- `d`: tsne (Figure 2 in the paper)
- `e` number of augmentations in sentence (Figure 4 in the paper)
