### ISSUE TITLE
Meaning of 0 and 1

### ISSUE THREAD

**Issue by tpinju00** [jasonwei20/eda_nlp#11]
Hi,

can you please explain to me why some sentences in dataset have 0 in front, and some have 1.

Thank you.

**Comment by jasonwei20** [comment]
They're the labels, which can vary depending on which dataset you are using (e.g., 0 is negative and 1 is positive for movie reviews).

**Comment by tpinju00** [comment]
If I'm working with FAQ dataset, should I delete the 0 and 1 or it doesn't matter?
