### ISSUE TITLE
Random insertion is not excluding words from the stop words list

### ISSUE THREAD

**Issue by Aid91** [jasonwei20/eda_nlp#14]
Hi, thanks for the code repository and the paper! 

I think that the idea behind Easy Data Augmentation is helpful and I am planning to port/adapt it such that it is usable for the German language as well.

Based on your paper random insertion is done in the following way:

> **Random Insertion (RI):** Find a random synonym of a random word in the sentence that **is not a stop word**. Insert that synonym into a random position in the sentence. Do this _n_ times.

However, by looking your implementation stop words are not excluded:

```
def random_insertion(words, n):
	new_words = words.copy()
	for _ in range(n):
		add_word(new_words)
	return new_words`
```
```
def add_word(new_words):
	synonyms = []
	counter = 0
	while len(synonyms) < 1:
		random_word = new_words[random.randint(0, len(new_words)-1)]
		synonyms = get_synonyms(random_word)
		counter += 1
		if counter >= 10:
			return
	random_synonym = synonyms[0]
	random_idx = random.randint(0, len(new_words)-1)
	new_words.insert(random_idx, random_synonym)
```

```
def eda(sentence, alpha_sr=0.1, alpha_ri=0.1, alpha_rs=0.1, p_rd=0.1, num_aug=9):
	
	sentence = get_only_chars(sentence)
	words = sentence.split(' ')
	words = [word for word in words if word is not '']
	num_words = len(words)
	
	augmented_sentences = []
	num_new_per_technique = int(num_aug/4)+1
	n_sr = max(1, int(alpha_sr*num_words))
	n_ri = max(1, int(alpha_ri*num_words))
	n_rs = max(1, int(alpha_rs*num_words))
         
       .........

	#ri
	for _ in range(num_new_per_technique):
		a_words = random_insertion(words, n_ri)
		augmented_sentences.append(' '.join(a_words))

        .........
```

Do you know how this affects the final results? Thanks!

**Comment by jasonwei20** [comment]
You're right actually, that was overlooked in the paper. 

I don't think it affects the results that much, you can probably do it either way.
