### ISSUE TITLE
Question/Suggestions

### ISSUE THREAD

**Issue by tannergilligan** [jasonwei20/eda_nlp#17]
Hi! I would like to say thank you for your contribution to the community. I've been going over your code, and have a few questions and potentially suggestions:

1) For the method "synonym_replacement()", why do you substitute all instance of a word for the selected synonym? For example, if you have the sentence "A B C B", and the select B=X as the synonym substitution, you will always end up with "A X C X". There's no possibility to generate "A B C X" or "A X C B" - was that intentional? If not, that could be a potential improvement. 

1.1) Another suggestion for "synonym_replacement()": Iterate through random indices of the list rather than the elements themselves. This will allow you to overwrite the words with their synonyms directly in the "new_words" list rather than creating a new list each time a substitution is made. Creating a new list can be expensive, especially if it's large or you're running it thousands of times.

2) For the method "add_words()",  you repeatedly select random indices as opposed to creating a random ordering of the indices - is there a reason for that? With the current code, there's the possibility that it selects the same index every time, and never adds a word even if the list contains a word with synonyms. Alternatively, you could shuffle a list of indices, and iterate through the list until you find one with a synonym. This would ensure you're not redundantly getting synonyms for the same word over and over, and ensure you always insert a word when the input list contains a word with synonyms.

3) For the method "random_swap()", a check to ensure the word last has at least 2 words would prevent unnecessary computation in single-word cases (small thing, but something I added in my code)

4) For the method "swap_words()", I basically have the same question as (2). In addition, I'm pretty sure you can greatly simplify the method to:

```
def swap_word(new_words):
    index1, index2 = random.sample(range(len(new_words)), 2)
    new_words[index1], new_words[index2] = new_words[index2], new_words[index1]
    return new_words
```

Please correct me if the above method doesn't do the same thing - it's what I'm using in my code and I'd prefer to not have missed something :)

5) I'm intrigued by this code snippet:
```
        # this is stupid but we need it, trust me
        sentence = ' '.join(new_words)
        new_words = sentence.split(' ')
```
Could you tell me what was happening that made this necessary? I'm sure you encountered some edge case that this fixed, but I'm curious what that was.

6) For the method "eda()", when the user specifies "num_aug=0", what are you trying to do in the "else" block at the end of the method? The output ends up being anywhere from 0 to num_aug sentences, depending on chance. Statistically, you will get on average 1 augmentation back, but this isn't guaranteed.

This is all meant as constructive criticism, so I hope you don't feel I'm being negative towards your work. I'd love to hear your feedback on these questions and thoughts; the work I'm doing is highly related to this topic, so I'm curious about some of the decisions you made. Thanks!

**Comment by jasonwei20** [comment]
Hi Tanner,
It's feedback like this that helps the community (i.e., me) learn, so thank you :)
1. That's probably better, yeah.
1.1 You're right.
2. Yeah I guess that's right, although I don't know if it will actually make a difference in performance.
3. Yep.
4. It looks like `random.sample` works without replacement, so you're right I think. Maybe there was an edge case when I first wrote it, but I don't remember.
5. Sometimes WordNet replaces a single word with a two-word synonym, in which case you need to separate the two words.
6. Yeah so for this one, I did some experiments where I wanted to generate say 1 augmented sentence per 4 real sentences (i.e., `num_aug=4`). Note that the output always includes the original sentence, so in this case, there will be on average 1.25 sentences (original + augmented) back.

If you'd like to submit a PR with any edits, I would be more than happy to review.
