### ISSUE TITLE
Confirmation abt data augmentation

### ISSUE THREAD

**Issue by littleflow3r** [jasonwei20/eda_nlp#19]
Hi @jasonwei20 thanks for the great work!

I want to confirm my understanding of data augmentation in your paper: 
In the experiment (RNN and CNN), do you ONLY use the output (the augmented data, train_aug_st.txt) for training? Or do you mix them (original training data + augmented training data from the original) and used them for training?
In other words, do your training data in the experiment (experiment +EDA) includes the original training data?

Thanks.

**Comment by jasonwei20** [comment]
You'll see that the training data in the experiment does include the original training data (i.e., they are mixed).

**Comment by littleflow3r** [comment]
Thanks for the answer. 
Sorry to reopen the issue, but I still have question.
So in the paper (Table 2), in the column Training set size, e.g. when n=500, it means the original model includes 500 training data, while for the +EDA model n becomes 500 + the augmented data (e.g. when n-aug = 4, n becomes 500 + (500*4) = 2500) ?

**Comment by jasonwei20** [comment]
That's right.

**Comment by littleflow3r** [comment]
Thanks!
