### ISSUE TITLE
How to change alpha?

### ISSUE THREAD

**Issue by romanovzky** [jasonwei20/eda_nlp#2]
Hi again,

It works like a charm!

Just a quick question, how do you change the alpha at runtime (as in an argument of the command). As I seen from `augment.py`:

```python
import argparse
ap = argparse.ArgumentParser()
ap.add_argument("--input", required=True, type=str, help="input file of unaugmented data")
ap.add_argument("--output", required=False, type=str, help="output file of unaugmented data")
ap.add_argument("--num_aug", required=False, type=int, help="number of augmented sentences per original sentence")
args = ap.parse_args()
```

This does not seem to be possible.

Cheers,
M

**Comment by romanovzky** [comment]
I see the different `alpha` are a parameter of the `eda` function. Any chance we can configure the inpute alphas through arguments or from a config file? (feature request)

**Comment by jasonwei20** [comment]
Hi Romanovsky,

Thanks for creating this issue. What a wonderful suggestion! I just included a parameter for changing alpha. Feel free to post another issue if anything else comes up.

Sincerely,
Jason
