### ISSUE TITLE
Possibility of masking some tokens?

### ISSUE THREAD

**Issue by ssp573** [jasonwei20/eda_nlp#20]
I am working on a problem with heavily imbalanced datasets. I want to use this tool to augment the positive class in my dataset. The problem is some of the tokens are critical to the problem I am trying to solve and I would like to mask those tokens for this tool. Is that currently possible?

**Comment by jasonwei20** [comment]
Yeah, you can just add an if statement that does not perturb the tokens that are critical to the task. The modification would probably be done in this file: https://github.com/jasonwei20/eda_nlp/blob/master/code/eda.py
