### ISSUE TITLE
random_insertion should take stop words into account

### ISSUE THREAD

**Issue by lorenz-haenggi-axa** [jasonwei20/eda_nlp#24]
https://github.com/jasonwei20/eda_nlp/blob/d75e8bd4631f4d93260cb291aa47852d8eacd51d/code/eda.py#L151

in your documentation you  are saying that for the "insert" you remove "stop words".
in the code it does not. 

I have not very often an random insert hit due to fact that possible stop words are not found in synonms.
And you to take only the noStopWords into account here
https://github.com/jasonwei20/eda_nlp/blob/d75e8bd4631f4d93260cb291aa47852d8eacd51d/code/eda.py#L160

**Comment by lorenz-haenggi-axa** [comment]
your EDA is cool - I have translated it into c# and use it for NLP data augmentation for our bot

**Comment by jasonwei20** [comment]
Ah yes, you're right here.
