### ISSUE TITLE
BERT + EDA ?

### ISSUE THREAD

**Issue by guotong1988** [jasonwei20/eda_nlp#25]
Will Random Swap (RS) and Random Deletion (RD) work well for BERT, as BERT is besed on contextual pre-training.

Thank you very much. @jasonwei20

**Comment by jasonwei20** [comment]
If you have a large dataset and are using BERT fine-tuning, the performance difference will probably be marginal. If your data size is small, however, it could be worth a try. I have not done a formal BERT + EDA experiment.

**Comment by lian6605** [comment]
I read the paper. EDA written by Jason Wei.
In this paper, it is said that the results in Bert won't go up much.
Will applying EDA to BERT produce better results in natural language processing?
