### ISSUE TITLE
performance gain of each eda method

### ISSUE THREAD

**Issue by YuBeomGon** [jasonwei20/eda_nlp#26]
Can I know the each performance gain per each eda method??

And in Synonym Replacement (SR), how can I get a similar word?

**Comment by sooooner** [comment]
@YuBeomGon 
I think you can adjust the application rate of each method by modifying the **alpha** and **num_new_per_technique** in code/eda.py's eda function.

**Comment by jasonwei20** [comment]
See figure 3 in the paper: https://arxiv.org/pdf/1901.11196.pdf
