### ISSUE TITLE
Mechanism to choose between EDA tasks

### ISSUE THREAD

**Issue by adimyth** [jasonwei20/eda_nlp#28]
Is there a mechanism to choose between the type of augmentation that I wish to apply to my data. Example - Sometimes, you might just want to apply Synonym Replacement (SR) and Random Deletion (RD), while ignoring the other two techniques (Random Insertion & Random Swap) as it may completely change the label. One dataset I could think of is [Corpus of Linguistic Acceptability(CoLA)](https://nyu-mll.github.io/CoLA/), where RI & RS I believe will change the target label.

In the current implementation the passed argument `alpha` is applied equally for each of the augmentation. Passing `alpha` for each of the technique as command line argument individually would allow fine grained control & will help achieve the desired task.

**Comment by lolo8304** [comment]
I also agree. I have implemented eg that ‘remove’ only works if number of words in sentence > 6 because it would change the meaning. 

Insertion of synonyms at another place is not an issue. 
I have then used different algo predictions if 3 or 4 algo are used

**Comment by jasonwei20** [comment]
Ah, you're right, COLA is a good example of a dataset where EDA might not the best type of augmentation to use. 

I'm not actively maintaining the repository right now but if you'd like to send a PR, I can certainly do a code review.
