### ISSUE TITLE
Augmenting non-english datasets

### ISSUE THREAD

**Issue by bernardohenz** [jasonwei20/eda_nlp#3]
Hello,

this idea of implementing such data augmentations in such an easy script is superb. I would like to use it in some of my applications. My main concern is that my dataset is on Portuguese-BR, and I would like to know what should I do for adapting your code.

There are already some embeddings trained in Portuguese ([link](http://nilc.icmc.usp.br/embeddings)), by having them, is it easy to adjust your code?

Again, congrats for the great work.

**Comment by jasonwei20** [comment]
You'd need some way to find synonyms. Whether this is by a k-nearest neighbors search in your word embeddings, or like WordNet in Portuguese, is up to you.
