### ISSUE TITLE
Semi-supervised

### ISSUE THREAD

**Issue by cuczy** [jasonwei20/eda_nlp#31]
In the semi-supervised field, first perform eda on labeled data
If I use 500 pieces of data in the fine-tuning stage, will the use of the eda method improve the results？ (the bert model is officially trained)
thank you very much!

**Comment by jasonwei20** [comment]
I don't know. Maybe? Seems like it could.

But if you're fine-tuning BERT in a vanilla fashion for supervised text classification, [this paper](https://arxiv.org/abs/2010.01764) says otherwise
