### ISSUE TITLE
About the test dataset

### ISSUE THREAD

**Issue by HaishuoFang** [jasonwei20/eda_nlp#5]
I am curious about your data process. I mean do you split the dataset to train and test datasets, then augment the train_dataset or augment all datasets firstly then split the dataset?
Because the only difference between these two processes is whether the test datasets include the augment data.

**Comment by jasonwei20** [comment]
The test datasets should not include augmented data. Please only augment training data.

**Comment by Ailing-Zou** [comment]
Your advice gives me another direction to augment my data, thanks.
