### ISSUE TITLE
Moderation of corpus might be required

### ISSUE THREAD

**Issue by surajpadhy** [jasonwei20/eda_nlp#6]
While trying out your code, which was infact very helpful in generating a lot of training data for my model, I found one of the generated sentence to be out of place.

**Provided sentence:**
5	let me start a task

**Output:**
5	let me start antiophthalmic factor a task
5	let me start a task
5	_**lashkar e taiba**_ me start a task
5	let me kickoff a task
5	let task start a me
5	let me start a task
5	let me start a task
5	task me start a let
5	let me start a labor
5	antiophthalmic factor let me start a task
5	let me start a task

Text marked in bold is a terrorist organization. You can find the details in the link below.
[https://en.wikipedia.org/wiki/Lashkar-e-Taiba](Lashkar-e-Taiba)

If possible can you please consider removing that name from synonyms of word "let"
random word for  let :  lashkar e taiba

**Parameters Used:**
--num_aug=10 --alpha=0.01

**Comment by jasonwei20** [comment]
It seems like let stands for a terrorist organization, unfortunately. Sorry to hear that, but these synonyms are generated by WordNet, which I do not have control over. The easiest way for you to solve this issue is to add 'let' to the list of stop words. Hope this helps!
