### ISSUE TITLE
Strange occurrences with I'm and It's (apostrophes)

### ISSUE THREAD

**Issue by AllBecomesGood** [jasonwei20/eda_nlp#7]
So I augmented my dataset and found some strange things happening:
- I'm standing on it
- It's in front of me
became
- i m standing on it
- it s in front of me
I don't know why it was split like that, and in fact I can't even reproduce this now anymore. At first I thought that I had some weird apostrophes, but my tests don't confirm that.

Basically I am creating this issue to ask if anyone had something like this happen or knows a possible cause?

**Comment by jasonwei20** [comment]
I would guess that you had some weird characters in there.
