### ISSUE TITLE
Could you please upload the data set?

### ISSUE THREAD

**Issue by heslowen** [jasonwei20/eda_nlp#9]
I spent lots of time on it but I still couldn't find them except the SST dataset.
Could you please upload the data set or send it to  heslowen@gmail.com?
thanks!

**Comment by jasonwei20** [comment]
CR and PC datasets: https://www.cs.uic.edu/~liub/FBS/sentiment-analysis.html
SUBJ dataset: http://www.cs.cornell.edu/people/pabo/movie-review-data/
TREC dataset: https://cogcomp.seas.upenn.edu/Data/QA/QC/

Just google the references next time.
